name = "Mailchimp"
nameId = "mailchimp"
categories = ["email"]
version = "0.1.0-alpha"
logo = "https://raw.githubusercontent.com/BusinessQL/businessql-app-mailchimp/main/images/logo.svg"

[settings]
  [[settings.fields]]
  label = "Data center"
  name = "dataCenter"
  type = "text"
  placeholder = "us6"

  [[settings.fields]]
  label = "API Key"
  name = "apiKey"
  type = "password"

  [[settings.fields]]
  label = "Default Group ID"
  name = "defaultGroupId"
  type = "text"

[developer]
nameId = "businessql"

[theme.colors]
primary = "#FADC44"
