[query]
  # get subscriber
  [query.getSubscriber]
  type = "api"
  url = "https://{data.dataCenter}.api.mailchimp.com/3.0/lists/{args.groupId}/members/{args.id|args.email}"
  method = "GET"

    [query.getSubscriber.headers]
      Authorization = "Bearer {data.apiKey}"

    [query.getSubscriber.response]
      [query.getSubscriber.response.success]
      id = "{{result.id}}"
      email = "{{result.email_address}}"
      name = "{{result.full_name}}"
      status = "{{result.status}}"
  
[mutation]
  # subscribe
  [mutation.subscribe]
  type = "api"
  url = "https://{data.dataCenter}.api.mailchimp.com/3.0/lists/{args.groupId}/members"
  method = "POST"

    [mutation.subscribe.headers]
      Authorization = "Bearer {data.apiKey}"

    [mutation.subscribe.data]
      email_address = "{{args.email}}"
      status = "subscribed"
      [mutation.subscribe.data.merge_fields]
      FNAME = "{{args.name|''}}"

    [mutation.subscribe.response]
      [mutation.subscribe.response.success]
      id = "{{result.id}}"
      email = "{{result.email_address}}"
      name = "{{result.full_name}}"
      status = "{{result.status}}"

  # update subscriber
  [mutation.updateSubscriber]
  type = "api"
  url = "https://{data.dataCenter}.api.mailchimp.com/3.0/lists/{args.groupId}/members/{args.id|args.email}"
  method = "PATCH"

    [mutation.updateSubscriber.headers]
      Authorization = "Bearer {data.apiKey}"

    [mutation.updateSubscriber.data]
      email_address = "{{args.email}}"
      status = "{{args.status|subscribed}}"
      [mutation.updateSubscriber.data.merge_fields]
      FNAME = "{{args.name|''}}"

    [mutation.updateSubscriber.response]
      [mutation.updateSubscriber.response.success]
      id = "{{result.id}}"
      email = "{{result.email_address}}"
      name = "{{result.full_name}}"
      status = "{{result.status}}"
